"""LinkedIn'de satis yapilabilecek sektorler: hangi sektore hangi hizmet satilir, o sektorde kime yazilir ve
LinkedIn aramasinda hangi kelimeler kullanilir. "Mesaj Gonder" sayfasindaki acilir liste buradan gelir.

Gruplar SATILACAK HIZMETI anlatir, kisinin nerede bulundugunu degil: kisiler her zaman LinkedIn'in kendi
aramasinda bulunur ve mesaj LinkedIn'den gider. MAPS = isletmeye yorum/harita gorunurlugu satilir,
SEO = organik arama trafigi satilir. Reklam yasagi olan meslekler (avukat, eczane) bilerek listeye alinmadi.
"""

MAPS = "maps"
SEO = "seo"
WEB = "web"
HAVUZLAR = (MAPS, SEO, WEB)

# Acilir listedeki grup basliklari: hangi hizmeti satacagini soyler
GRUP_ADLARI = {
    MAPS: "Google Maps itibar yönetimi satacağın sektörler",
    SEO: "SEO (organik trafik) satacağın sektörler",
    WEB: "Web sitesi yapımı ve aylık bakım satacağın sektörler",
}
GRUP_KISA = {MAPS: "Maps hizmeti", SEO: "SEO hizmeti", WEB: "Web sitesi"}
GRUP_ACIKLAMALARI = {
    MAPS: "Bu sektörlerde müşteri işletmeyi Google haritasından ve yorumlardan seçiyor; sen yorum yönetimi ve harita görünürlüğü satıyorsun.",
    SEO: "Bu sektörlerde müşteri Google'da arayıp siteye giriyor; sen arama sırasını ve organik trafiği satıyorsun.",
    WEB: "Bu sektörlerde iş, siteyle anlatılıyor: site ya hiç yok ya eski ve güncelleyen kimse yok; sen site yapımını ve aylık bakımı satıyorsun.",
}

# Sirket buyuklugune gore dogru muhatap kurali puanlamada isliyor; buradaki paketler o kurala uygun secildi
ROL_PAKETLERI = {
    "yerel": ["Founder", "Co-Founder", "Owner", "General Manager", "Marketing Manager"],
    "yerel_zincir": ["Founder", "Co-Founder", "Owner", "General Manager", "Marketing Manager", "Marketing Director",
                     "Head of Marketing", "Brand Manager"],
    "saglik": ["Founder", "Owner", "General Manager", "International Patient Manager", "Marketing Manager",
               "Digital Marketing Manager"],
    "uretim": ["Founder", "CEO", "General Manager", "Managing Director", "Export Manager", "Marketing Manager",
               "Digital Marketing Manager", "Business Development Director"],
    "b2b": ["Founder", "CEO", "General Manager", "Head of Marketing", "Marketing Manager", "Digital Marketing Manager",
            "Business Development Director"],
    "eticaret": ["Founder", "CEO", "General Manager", "E-commerce Manager", "Digital Marketing Manager",
                 "Marketing Manager", "Head of Marketing"],
    "proje": ["Founder", "Co-Founder", "Owner", "General Manager", "Marketing Director", "Head of Marketing",
              "Marketing Manager", "Sales Director"],
}

_KUCUK = ["11-50", "51-200"]
_ORTA = ["11-50", "51-200", "201-500"]

SEKTORLER = [
    # ---------------- Google Maps: yerel, mekana musteri gelen isler ----------------
    {"kod": "oteller", "ad": "Oteller ve konaklama", "hizmet": MAPS, "hizmetler": ["maps", "seo"],
     "paket": "yerel_zincir", "boyutlar": _KUCUK, "kelimeler": ["otel", "hotel", "resort", "konaklama", "butik otel"],
     "aciklama": "Rezervasyonun çoğu Google aramasından ve haritadan geliyor; yorum puanı doğrudan doluluğa etki ediyor."},
    {"kod": "restoran", "ad": "Restoran, kafe ve zincirler", "hizmet": MAPS, "hizmetler": ["maps"],
     "paket": "yerel_zincir", "boyutlar": _KUCUK, "kelimeler": ["restoran", "restaurant", "kafe", "cafe", "lokanta"],
     "aciklama": "Masa doluluğu yakındaki restoran aramalarına ve yorumlara bağlı; tek bir kötü yorum ciroyu düşürüyor."},
    {"kod": "pastane", "ad": "Pastane, fırın ve tatlıcılar", "hizmet": MAPS, "hizmetler": ["maps"],
     "paket": "yerel_zincir", "boyutlar": _KUCUK, "kelimeler": ["pastane", "fırın", "bakery", "tatlıcı", "pastacılık"],
     "aciklama": "Şubeye gelen müşteri önce haritaya bakıyor; yorum ve fotoğraf düzeni doğrudan ziyaret getiriyor."},
    {"kod": "otomotiv", "ad": "Otomotiv bayi ve servis", "hizmet": MAPS, "hizmetler": ["maps"],
     "paket": "yerel_zincir", "boyutlar": _ORTA,
     "kelimeler": ["otomotiv", "automotive", "oto servis", "bayi", "yetkili servis"],
     "aciklama": "Servis randevusu ve showroom ziyareti aramayla başlıyor; yorumlar pahalı işlerde güven veriyor."},
    {"kod": "rentacar", "ad": "Araç kiralama ve filo", "hizmet": MAPS, "hizmetler": ["maps", "seo"], "paket": "yerel",
     "boyutlar": _KUCUK, "kelimeler": ["araç kiralama", "rent a car", "oto kiralama", "filo kiralama"],
     "aciklama": "Şehir ve havalimanı aramalarında üst sırada olmak doğrudan kiralama demek."},
    {"kod": "guzellik", "ad": "Güzellik ve estetik merkezleri", "hizmet": MAPS, "hizmetler": ["maps"], "paket": "yerel",
     "boyutlar": _KUCUK, "kelimeler": ["güzellik merkezi", "estetik", "beauty", "cilt bakım", "medikal estetik"],
     "aciklama": "Randevular haritadan ve yorumlardan geliyor. Sağlıkta reklam kısıtı var: mesajda tedavi ve fiyat vaadi yok."},
    {"kod": "kuafor", "ad": "Kuaför ve berber zincirleri", "hizmet": MAPS, "hizmetler": ["maps"], "paket": "yerel",
     "boyutlar": _KUCUK, "kelimeler": ["kuaför", "berber", "saç tasarım", "hair studio"],
     "aciklama": "Semt aramalarında ilk üçte olmak ve yorum puanı, koltuk doluluğunu belirliyor."},
    {"kod": "dis", "ad": "Diş klinikleri", "hizmet": MAPS, "hizmetler": ["maps", "seo"], "paket": "saglik",
     "boyutlar": _KUCUK, "kelimeler": ["diş kliniği", "dental", "ağız ve diş sağlığı", "implant"],
     "aciklama": "Hasta yakınındaki diş kliniğini arıyor. Sağlıkta reklam kısıtı var: mesajda tedavi ve fiyat vaadi yok."},
    {"kod": "klinik", "ad": "Klinik ve tıp merkezleri", "hizmet": MAPS, "hizmetler": ["maps", "seo"], "paket": "saglik",
     "boyutlar": _KUCUK, "kelimeler": ["klinik", "tıp merkezi", "poliklinik", "medical center"],
     "aciklama": "Randevu trafiği haritadan geliyor; yorum yönetimi hasta güvenini etkiliyor (reklam kısıtına dikkat)."},
    {"kod": "saglik_turizmi", "ad": "Sağlık turizmi (saç ekimi, estetik)", "hizmet": SEO, "hizmetler": ["seo", "maps"],
     "paket": "saglik", "boyutlar": _KUCUK,
     "kelimeler": ["sağlık turizmi", "health tourism", "medical tourism", "saç ekimi", "hair transplant"],
     "aciklama": "Hasta yurt dışından Google'dan geliyor; İngilizce organik trafik doğrudan hasta demek."},
    {"kod": "veteriner", "ad": "Veteriner ve pet hizmetleri", "hizmet": MAPS, "hizmetler": ["maps"], "paket": "yerel",
     "boyutlar": _KUCUK, "kelimeler": ["veteriner", "pet kliniği", "petshop", "animal hospital"],
     "aciklama": "Acil arama çoğunlukla haritadan yapılıyor; en yakın ve en iyi yorumlu klinik kazanıyor."},
    {"kod": "spor", "ad": "Spor salonu, fitness ve stüdyolar", "hizmet": MAPS, "hizmetler": ["maps"],
     "paket": "yerel_zincir", "boyutlar": _KUCUK,
     "kelimeler": ["spor salonu", "fitness", "gym", "pilates", "yoga stüdyo"],
     "aciklama": "Üyelik kararı semt aramasıyla başlıyor; yorumlar ve fotoğraflar doğrudan üye getiriyor."},
    {"kod": "ozel_egitim", "ad": "Özel okul, kolej ve kurslar", "hizmet": MAPS, "hizmetler": ["maps", "seo"],
     "paket": "yerel_zincir", "boyutlar": _KUCUK,
     "kelimeler": ["özel okul", "kolej", "dil okulu", "kurs merkezi", "etüt merkezi"],
     "aciklama": "Veli önce Google'da arıyor ve yorumları okuyor; kayıt dönemi görünürlüğü doğrudan kayda dönüyor."},
    {"kod": "kres", "ad": "Kreş ve anaokulları", "hizmet": MAPS, "hizmetler": ["maps"], "paket": "yerel",
     "boyutlar": _KUCUK, "kelimeler": ["kreş", "anaokulu", "preschool", "day care"],
     "aciklama": "Veli mahalle araması yapıyor; yorumlar güven kararını belirliyor."},
    {"kod": "surucu_kursu", "ad": "Sürücü kursları", "hizmet": MAPS, "hizmetler": ["maps"], "paket": "yerel",
     "boyutlar": _KUCUK, "kelimeler": ["sürücü kursu", "ehliyet kursu", "driving school"],
     "aciklama": "Kayıtların tamamı yerel aramadan geliyor; harita sırası doğrudan öğrenci demek."},
    {"kod": "emlak_ofis", "ad": "Emlak ofisleri", "hizmet": MAPS, "hizmetler": ["maps", "seo"],
     "paket": "yerel_zincir", "boyutlar": _KUCUK,
     "kelimeler": ["emlak", "emlak ofisi", "real estate agency", "gayrimenkul danışmanlık"],
     "aciklama": "Portföy almak için bölgede bilinir olmak gerekiyor; harita ve yorumlar satıcıyı ofise getiriyor."},
    {"kod": "dugun", "ad": "Düğün, davet ve organizasyon", "hizmet": MAPS, "hizmetler": ["maps"], "paket": "yerel",
     "boyutlar": _KUCUK, "kelimeler": ["düğün salonu", "organizasyon", "davet", "kır düğünü", "event"],
     "aciklama": "Çift önce Google'dan salon arıyor; yorumlar ve fotoğraflar randevuyu belirliyor."},
    {"kod": "fotograf", "ad": "Fotoğraf ve video stüdyoları", "hizmet": MAPS, "hizmetler": ["maps", "web"],
     "paket": "yerel", "boyutlar": _KUCUK,
     "kelimeler": ["fotoğraf stüdyosu", "photography", "video prodüksiyon", "prodüksiyon"],
     "aciklama": "İş çoğunlukla yerel aramadan ve referanstan geliyor; görünürlük doğrudan çekim demek."},
    {"kod": "tadilat", "ad": "Tadilat, dekorasyon ve mobilya mağazaları", "hizmet": MAPS, "hizmetler": ["maps", "seo"],
     "paket": "yerel", "boyutlar": _KUCUK,
     "kelimeler": ["tadilat", "dekorasyon", "mobilya", "mutfak dolabı", "iç dekorasyon"],
     "aciklama": "Yüksek bütçeli işler yakındaki firma aramasıyla başlıyor; yorumlar teklif çağrısını getiriyor."},
    {"kod": "temizlik", "ad": "Temizlik ve ilaçlama şirketleri", "hizmet": MAPS, "hizmetler": ["maps"], "paket": "yerel",
     "boyutlar": _KUCUK, "kelimeler": ["temizlik şirketi", "halı yıkama", "ilaçlama", "cleaning services"],
     "aciklama": "Talep anlık ve yerel; haritada üstte olan telefonu alıyor."},
    {"kod": "nakliyat", "ad": "Evden eve nakliyat", "hizmet": MAPS, "hizmetler": ["maps", "seo"], "paket": "yerel",
     "boyutlar": _KUCUK, "kelimeler": ["evden eve nakliyat", "nakliyat", "taşımacılık", "moving company"],
     "aciklama": "Müşteri tek seferlik ve acil arıyor; harita sırası ve yorum puanı işi kimin alacağını belirliyor."},
    {"kod": "perakende", "ad": "Optik, kuyumcu ve mağaza zincirleri", "hizmet": MAPS, "hizmetler": ["maps"],
     "paket": "yerel_zincir", "boyutlar": _KUCUK,
     "kelimeler": ["optik", "gözlükçü", "kuyumcu", "mağaza zinciri", "perakende"],
     "aciklama": "Mağazaya gelen müşteri önce haritaya bakıyor; şube bilgileri ve yorumlar ziyaret getiriyor."},
    {"kod": "catering", "ad": "Catering ve toplu yemek", "hizmet": MAPS, "hizmetler": ["maps", "seo"],
     "paket": "yerel_zincir", "boyutlar": _ORTA,
     "kelimeler": ["catering", "toplu yemek", "yemek fabrikası", "food service"],
     "aciklama": "Kurumsal müşteri Google'dan araştırıyor; görünürlük ve yorumlar teklif listesine girmeyi sağlıyor."},
    {"kod": "turizm_acente", "ad": "Tur ve seyahat acenteleri", "hizmet": MAPS, "hizmetler": ["maps", "seo"],
     "paket": "yerel", "boyutlar": _KUCUK,
     "kelimeler": ["seyahat acentesi", "tur operatörü", "travel agency", "tur şirketi"],
     "aciklama": "Tur satışı aramadan başlıyor; yorumlar ve harita görünürlüğü doğrudan rezervasyon getiriyor."},
    {"kod": "teknik_servis", "ad": "Teknik servis ve tamir zincirleri", "hizmet": MAPS, "hizmetler": ["maps"],
     "paket": "yerel", "boyutlar": _KUCUK,
     "kelimeler": ["teknik servis", "yetkili servis", "beyaz eşya servisi", "tamir"],
     "aciklama": "Arıza anında en yakın ve en iyi yorumlu servis aranıyor; harita sırası doğrudan iş demek."},

    # ---------------- SEO: Google'da organik trafikle musteri bulan isler ----------------
    {"kod": "uretici_makine", "ad": "Makine ve ekipman üreticileri", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "uretim", "boyutlar": _ORTA, "kelimeler": ["makine", "machinery", "ekipman", "imalat", "manufacturing"],
     "aciklama": "Alıcı ürünü Türkçe ve İngilizce aramayla buluyor; teknik sayfalar yurt dışından talep getiriyor."},
    {"kod": "uretici_tekstil", "ad": "Tekstil ve hazır giyim üreticileri", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "uretim", "boyutlar": _ORTA, "kelimeler": ["tekstil", "textile", "konfeksiyon", "hazır giyim", "örme"],
     "aciklama": "Yurt dışı alıcı tedarikçiyi Google'dan tarıyor; İngilizce görünürlük doğrudan sipariş demek."},
    {"kod": "uretici_gida", "ad": "Gıda üreticileri", "hizmet": SEO, "hizmetler": ["seo", "web"], "paket": "uretim",
     "boyutlar": _ORTA, "kelimeler": ["gıda", "food", "gıda sanayi", "gıda üretim", "food manufacturer"],
     "aciklama": "İhracat ve zincir market talepleri aramadan geliyor; ürün sayfaları alıcıyı siteye çekiyor."},
    {"kod": "uretici_kimya", "ad": "Kimya, plastik ve boya sanayi", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "uretim", "boyutlar": _ORTA, "kelimeler": ["kimya", "chemical", "plastik", "boya", "polimer"],
     "aciklama": "Satın almacı ürün adını aratıyor; teknik içerik ve görünürlük teklif çağrısı getiriyor."},
    {"kod": "uretici_metal", "ad": "Metal, döküm ve sac işleme", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "uretim", "boyutlar": _ORTA, "kelimeler": ["metal", "döküm", "sac işleme", "çelik", "steel"],
     "aciklama": "Fason iş arayan sanayi müşterisi Google'dan tedarikçi buluyor."},
    {"kod": "uretici_mobilya", "ad": "Mobilya üreticileri", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "uretim", "boyutlar": _ORTA,
     "kelimeler": ["mobilya üretim", "furniture manufacturer", "mobilya fabrikası", "mobilya sanayi"],
     "aciklama": "Proje ve ihracat talepleri aramadan geliyor; katalog sayfaları organik trafik yaratıyor."},
    {"kod": "ambalaj", "ad": "Ambalaj sanayi", "hizmet": SEO, "hizmetler": ["seo", "web"], "paket": "uretim",
     "boyutlar": _ORTA, "kelimeler": ["ambalaj", "packaging", "karton ambalaj", "etiket", "esnek ambalaj"],
     "aciklama": "Her üretici ambalaj arıyor; ürün bazlı aramalarda üstte olmak sürekli talep demek."},
    {"kod": "yapi_malzeme", "ad": "Yapı malzemeleri üreticileri", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "uretim", "boyutlar": _ORTA,
     "kelimeler": ["yapı malzemeleri", "building materials", "seramik", "cephe", "yalıtım"],
     "aciklama": "Müteahhit ve mimar ürünü aramayla buluyor; teknik sayfalar bayi ve proje talebi getiriyor."},
    {"kod": "ihracatci", "ad": "İhracatçı firmalar", "hizmet": SEO, "hizmetler": ["seo", "web"], "paket": "uretim",
     "boyutlar": _ORTA, "kelimeler": ["ihracat", "export", "dış ticaret", "ihracatçı", "foreign trade"],
     "aciklama": "Yurt dışı alıcı fuardan çok Google'dan tedarikçi tarıyor; İngilizce site doğrudan talep getiriyor."},
    {"kod": "lojistik", "ad": "Lojistik ve uluslararası taşımacılık", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "b2b", "boyutlar": _ORTA,
     "kelimeler": ["lojistik", "logistics", "freight", "forwarder", "uluslararası nakliye"],
     "aciklama": "Yük sahibi rota ve hizmet aramasıyla firma seçiyor; organik trafik doğrudan teklif demek."},
    {"kod": "insaat", "ad": "İnşaat ve müteahhitlik", "hizmet": SEO, "hizmetler": ["seo", "web"], "paket": "proje",
     "boyutlar": _ORTA, "kelimeler": ["inşaat", "construction", "müteahhit", "taahhüt", "yapı"],
     "aciklama": "Referans ve görünürlük yeni proje çağrısı getiriyor; site ve arama sırası güven veriyor."},
    {"kod": "mimarlik", "ad": "Mimarlık ve iç mimarlık", "hizmet": WEB, "hizmetler": ["web", "seo"], "paket": "proje",
     "boyutlar": _KUCUK,
     "kelimeler": ["mimarlık", "architecture", "iç mimari", "interior design", "mimarlık ofisi"],
     "aciklama": "Portföyü gösteren site doğrudan iş getiriyor; proje aramalarında görünmek müşteri demek."},
    {"kod": "gayrimenkul_proje", "ad": "Gayrimenkul geliştirme ve proje satış", "hizmet": SEO,
     "hizmetler": ["seo", "web"], "paket": "proje", "boyutlar": _ORTA,
     "kelimeler": ["gayrimenkul", "real estate", "konut projesi", "proje satış"],
     "aciklama": "Alıcı projeyi aramayla buluyor; organik trafik doğrudan satış görüşmesi demek."},
    {"kod": "eticaret", "ad": "E-ticaret şirketleri", "hizmet": SEO, "hizmetler": ["seo"], "paket": "eticaret",
     "boyutlar": _ORTA, "kelimeler": ["e-ticaret", "e-commerce", "online satış", "marketplace", "online mağaza"],
     "aciklama": "Reklam maliyeti arttıkça organik trafik kâr demek; kategori sayfaları doğrudan satış getiriyor."},
    {"kod": "yazilim", "ad": "Yazılım ve teknoloji şirketleri", "hizmet": SEO, "hizmetler": ["seo"], "paket": "b2b",
     "boyutlar": _ORTA, "kelimeler": ["yazılım", "software", "teknoloji", "bilişim", "SaaS"],
     "aciklama": "Alıcı çözüm adıyla arıyor; içerik ve arama sırası demo talebi getiriyor."},
    {"kod": "danismanlik", "ad": "Danışmanlık firmaları", "hizmet": WEB, "hizmetler": ["web", "seo"], "paket": "b2b",
     "boyutlar": _KUCUK, "kelimeler": ["danışmanlık", "consulting", "yönetim danışmanlığı", "müşavirlik"],
     "aciklama": "Güven satan iş; site ve arama görünürlüğü doğrudan görüşme talebi getiriyor."},
    {"kod": "muhasebe", "ad": "Mali müşavirlik ve muhasebe", "hizmet": SEO, "hizmetler": ["seo", "web"], "paket": "b2b",
     "boyutlar": _KUCUK, "kelimeler": ["mali müşavir", "muhasebe", "denetim", "accounting"],
     "aciklama": "Yeni şirket kuranlar aramayla müşavir buluyor; şehir bazlı görünürlük müşteri getiriyor."},
    {"kod": "sigorta", "ad": "Sigorta acente ve brokerleri", "hizmet": SEO, "hizmetler": ["seo", "web"], "paket": "b2b",
     "boyutlar": _KUCUK, "kelimeler": ["sigorta", "insurance", "sigorta acentesi", "broker"],
     "aciklama": "Poliçe arayan kişi Google'dan başlıyor; teklif formuna gelen organik trafik doğrudan gelir."},
    {"kod": "enerji", "ad": "Enerji ve güneş enerjisi (GES)", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "b2b", "boyutlar": _ORTA,
     "kelimeler": ["enerji", "güneş enerjisi", "solar", "GES", "yenilenebilir enerji"],
     "aciklama": "Yatırım kararı araştırmayla başlıyor; bilgi içeriği yüksek bütçeli talep getiriyor."},
    {"kod": "medikal", "ad": "Medikal cihaz ve sağlık ürünleri", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "b2b", "boyutlar": _ORTA, "kelimeler": ["medikal", "medical device", "tıbbi cihaz", "medikal ürün"],
     "aciklama": "Hastane ve bayi ürünü aramayla buluyor; teknik sayfalar bayilik ve ihale talebi getiriyor."},
    {"kod": "tarim", "ad": "Tarım, sera ve gıda ihracatı", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "uretim", "boyutlar": _ORTA, "kelimeler": ["tarım", "agriculture", "sera", "tohum", "tarım ürünleri"],
     "aciklama": "Yurt dışı alıcı ürün ve sezon aramasıyla tedarikçi buluyor."},
    {"kod": "otomotiv_yedek", "ad": "Otomotiv yedek parça sanayi", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "uretim", "boyutlar": _ORTA,
     "kelimeler": ["yedek parça", "spare parts", "otomotiv sanayi", "oto yedek parça"],
     "aciklama": "Parça ve ürün aramaları çok yoğun; organik trafik doğrudan toptan talep demek."},
    {"kod": "ik", "ad": "İnsan kaynakları ve istihdam firmaları", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "b2b", "boyutlar": _KUCUK,
     "kelimeler": ["insan kaynakları", "human resources", "istihdam", "işe alım", "recruitment"],
     "aciklama": "Hem şirket hem aday aramayla geliyor; görünürlük iki taraflı müşteri getiriyor."},
    {"kod": "tesis_yonetimi", "ad": "Tesis yönetimi ve kurumsal hizmetler", "hizmet": SEO, "hizmetler": ["seo"],
     "paket": "b2b", "boyutlar": _ORTA,
     "kelimeler": ["tesis yönetimi", "facility management", "kurumsal hizmet", "outsourcing"],
     "aciklama": "Kurumsal alıcı tedarikçiyi aramayla listeliyor; görünürlük ihale davetine dönüşüyor."},
    {"kod": "egitim_tek", "ad": "Eğitim teknolojileri ve online kurslar", "hizmet": SEO, "hizmetler": ["seo"],
     "paket": "eticaret", "boyutlar": _KUCUK,
     "kelimeler": ["online eğitim", "e-learning", "edtech", "uzaktan eğitim", "online kurs"],
     "aciklama": "Kursiyer konu aramasıyla geliyor; organik trafik reklam bütçesinden ucuz satış demek."},
    {"kod": "fuar", "ad": "Fuar, kongre ve etkinlik şirketleri", "hizmet": SEO, "hizmetler": ["seo", "web"],
     "paket": "b2b", "boyutlar": _KUCUK, "kelimeler": ["fuar", "exhibition", "kongre", "etkinlik yönetimi"],
     "aciklama": "Katılımcı ve ziyaretçi etkinliği aramayla buluyor; görünürlük doğrudan stant satışı demek."},
    {"kod": "matbaa", "ad": "Matbaa ve baskı", "hizmet": SEO, "hizmetler": ["seo", "web"], "paket": "uretim",
     "boyutlar": _KUCUK, "kelimeler": ["matbaa", "baskı", "printing", "dijital baskı"],
     "aciklama": "Kurumsal müşteri iş bazlı arama yapıyor; ürün sayfaları sürekli teklif talebi getiriyor."},
    {"kod": "guvenlik", "ad": "Güvenlik hizmetleri", "hizmet": SEO, "hizmetler": ["seo", "web"], "paket": "b2b",
     "boyutlar": _ORTA, "kelimeler": ["güvenlik hizmetleri", "özel güvenlik", "security services"],
     "aciklama": "Site ve fabrika yönetimleri tedarikçiyi aramayla buluyor; görünürlük sözleşme getiriyor."},

    # ---------------- Web sitesi yapimi ve aylik bakim satilan isler ----------------
    {"kod": "girisim", "ad": "Yeni kurulan şirketler ve girişimler", "hizmet": WEB, "hizmetler": ["web", "seo"],
     "paket": "b2b", "boyutlar": _KUCUK, "kelimeler": ["startup", "girişim", "teknoloji girişimi", "yeni marka"],
     "aciklama": "Şirket yeni: sitesi ya yok ya da aceleye gelmiş. Site kurulumu ve aylık bakım birlikte satılır."},
    {"kod": "peyzaj", "ad": "Peyzaj ve bahçe tasarımı", "hizmet": WEB, "hizmetler": ["web", "seo"], "paket": "yerel",
     "boyutlar": _KUCUK, "kelimeler": ["peyzaj", "landscape", "bahçe tasarım", "peyzaj mimarlığı"],
     "aciklama": "İşi göze hitap ediyor ama çoğunun sitesi yok; proje fotoğraflarını gösteren site doğrudan iş getiriyor."},
    {"kod": "oto_galeri", "ad": "Oto galeri ve ikinci el araç", "hizmet": WEB, "hizmetler": ["web", "maps"],
     "paket": "yerel_zincir", "boyutlar": _KUCUK,
     "kelimeler": ["oto galeri", "ikinci el araç", "araç alım satım", "car dealer"],
     "aciklama": "Araç listesini güncel tutan bir site ve aylık bakım şart; çoğu sadece ilan sitelerine bağımlı."},
    {"kod": "franchise", "ad": "Franchise veren markalar", "hizmet": WEB, "hizmetler": ["web", "seo"], "paket": "b2b",
     "boyutlar": _ORTA, "kelimeler": ["franchise", "bayilik", "şube ağı", "marka franchise"],
     "aciklama": "Bayi adayı önce siteye bakıyor; başvuru sayfası ve düzenli güncellenen şube listesi gerekiyor."},
    {"kod": "toptanci", "ad": "Toptancı ve dağıtım şirketleri", "hizmet": WEB, "hizmetler": ["web", "seo"],
     "paket": "b2b", "boyutlar": _ORTA, "kelimeler": ["toptan", "distribütör", "dağıtım", "wholesale"],
     "aciklama": "Bayi ve perakendeci ürün listesini siteden görmek istiyor; katalog sitesi ve aylık güncelleme satılır."},
    {"kod": "muhendislik", "ad": "Mühendislik ve proje ofisleri", "hizmet": WEB, "hizmetler": ["web", "seo"],
     "paket": "b2b", "boyutlar": _ORTA, "kelimeler": ["mühendislik", "engineering", "proje ofisi", "otomasyon"],
     "aciklama": "İhaleye ve kurumsal müşteriye giriyorlar; referansları gösteren ciddi bir site güven veriyor."},
    {"kod": "dernek", "ad": "Dernek, vakıf ve meslek odaları", "hizmet": WEB, "hizmetler": ["web"], "paket": "b2b",
     "boyutlar": _KUCUK, "kelimeler": ["dernek", "vakıf", "meslek odası", "federasyon"],
     "aciklama": "Duyuru ve üyelik sayfaları sürekli güncelleniyor; site yapımı ve aylık bakım birlikte gidiyor."},
    {"kod": "villa_kiralama", "ad": "Villa, apart ve tatil kiralama", "hizmet": WEB, "hizmetler": ["web", "seo"],
     "paket": "yerel", "boyutlar": _KUCUK,
     "kelimeler": ["villa kiralama", "apart otel", "tatil kiralama", "vacation rental"],
     "aciklama": "Komisyonlu sitelere mahkûmlar; kendi rezervasyon sitesi doğrudan kâr demek, sezon boyu bakım ister."},
    {"kod": "spor_kulup", "ad": "Spor kulüpleri ve akademiler", "hizmet": WEB, "hizmetler": ["web", "maps"],
     "paket": "yerel_zincir", "boyutlar": _KUCUK,
     "kelimeler": ["spor kulübü", "futbol akademi", "spor akademisi", "basketbol kulübü"],
     "aciklama": "Kayıt, aidat ve duyuru sayfaları lazım; sezonluk güncelleme aylık bakım anlaşmasına dönüyor."},
]

# Ilk testte calisan 6 grup (stratejideki gruplar)
BASLANGIC_KODLARI = ["oteller", "otomotiv", "restoran", "uretici_makine", "gayrimenkul_proje", "insaat"]

# Onceki surumde bu adlarla kurulmus kampanyalari sektorlere baglamak icin
ESKI_KAMPANYA_ADLARI = {
    "Oteller": "oteller",
    "Otomotiv bayi ve servis": "otomotiv",
    "Restoran grupları": "restoran",
    "Üretici ve ihracatçılar": "uretici_makine",
    "Gayrimenkul şirketleri": "gayrimenkul_proje",
    "İnşaat ve mimarlık": "insaat",
}

_KODA_GORE = {s["kod"]: s for s in SEKTORLER}


def sektor(kod: str):
    return _KODA_GORE.get(kod)


def gruplu_sektorler() -> list:
    """[(hizmet, [sektor, ...]), ...] — acilir listede basliklarla gostermek icin."""
    return [(hizmet, [s for s in SEKTORLER if s["hizmet"] == hizmet]) for hizmet in HAVUZLAR]


def kampanya_verisi(kod: str, mesaj: str, hedef: int = 100, sehirler=None, ilceler=None) -> dict:
    """Sektoru, kampanya tablosuna yazilacak veriye cevirir."""
    s = _KODA_GORE[kod]
    return {
        "ad": s["ad"],
        "hizmetler": list(s["hizmetler"]),
        "sektor_kelimeleri": list(s["kelimeler"]),
        "sirket_boyutlari": list(s["boyutlar"]),
        "roller": list(ROL_PAKETLERI[s["paket"]]),
        "sehir": list(sehirler or []),
        "ilceler": list(ilceler or []),
        "hedef": hedef,
        "ilk_mesaj": mesaj,
        "kaynak": kod,
    }
